# Generated by Django 5.0.1 on 2024-02-12 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.TextField()),
                ('ticket_number', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('TO DO', 'To Do'), ('HOLD', 'Hold'), ('IN PROGRESS', 'In Progress'), ('REVIEW', 'Review'), ('DONE', 'Done')], default='TO DO', max_length=20)),
                ('type', models.CharField(choices=[('BUG', 'Bug'), ('FEATURE', 'Feature')], max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_tasks', to='employees.employee')),
            ],
        ),
    ]
